PhotoArt/config/routes.rb
Photoart::Application.routes.draw do
  
  resources :users, :user_sessions
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  resources :users do
    resources :imgs
  end
  root :to => "users#index"

end

PhotoArt/app/models/addfields.rb
class Addfields < ActiveRecord::Base
  attr_accessible :crypted_password, :password_salt, :persistence_token, :username, :password, :password_confirmation
  acts_as_authentic
end

PhotoArt/app/models/img.rb
class Img < ActiveRecord::Base
  attr_accessible :description, :public, :user_id, :pic
  belongs_to :user
  has_attached_file :pic, :styles => 
           { :front => "240x300>", :medium => "240x300>", :thumb => "100x100>" }
  
end

PhotoArt/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :about, :email, :location, :name, :username, :password, :password_confirmation
  validates :name, :presence => true
  acts_as_authentic
  has_many :imgs
end

PhotoArt/app/models/user_session.rb
class UserSession < Authlogic::Session::Base
	def to_key
		new_record? ? nil : [ self.send(self.class.primary_key) ]
	end
	def persisted?
		false
	end
end

PhotoArt/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   protect_from_forgery
	
	helper_method :current_user
	private
	def current_user_session
		return @current_user_session if defined?(@current_user_session)
		@current_user_session = UserSession.find
	end
	def current_user
		return @current_user if defined?(@current_user)
		@current_user = current_user_session && current_user_session.record
	end
end

PhotoArt/app/controllers/imgs_controller.rb
class ImgsController < ApplicationController

	respond_to :html, :xml, :js

	def create

		@user = User.find(params[:user_id])
		@img = @user.imgs.new(params[:img])

		if @img.save
			flash[:notification] = "Img uploades."
			redirect_to user_url(@user)
		else
			flash[:error] = "Img not uploades."
			redirect_to user_url(@user)
		end

	end

end

PhotoArt/app/controllers/pages_controller_controller.rb
class PagesControllerController < ApplicationController

	def home
  	end

  	def about
  	end

  	def contact
  	end

end

PhotoArt/app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
 
# GET /user_sessions/new
# GET /user_sessions/new.xml
  def new
    @user_session = UserSession.new
     
    respond_to do |format|
    format.html # new.html.erb
    format.xml { render :xml => @user_session }
    end
  end
   
  # POST /user_sessions
  # POST /user_sessions.xml
  def create
    @user_session = UserSession.new(params[:user_session])
     
      respond_to do |format|
      if @user_session.save
        format.html { redirect_to(:users, :notice => 'Login Successful') }
        format.xml { render :xml => @user_session, :status => :created, :location => @user_session }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @user_session.errors, :status => :unprocessable_entity }
      end
    end
  end
   
  # DELETE /user_sessions/1
  # DELETE /user_sessions/1.xml
  def destroy
    @user_session = UserSession.find
    @user_session.destroy
     
    respond_to do |format|
      format.html { redirect_to(:users, :notice => 'Goodbye!') }
      format.xml { head :ok }
    end
  end
end

PhotoArt/app/controllers/users_controller.rb
class UsersController < ApplicationController

	respond_to :html, :xml, :js

	def index
		respond_with(@users = User.all)

	end

	def new 
		@user = User.new

    	respond_to do |format|
      		format.html # new.html.erb
      		format.json { render json: @user }
    	end
	end

	def create
		@user = User.new(params[:user])
 
	    respond_to do |format|
	    if @user.save
	    	format.html { redirect_to(:users, :notice => 'Registration successfull.') }
	    	format.xml { render :xml => @user, :status => :created, :location => @user }
	    else
	    	format.html { render :action => "new" }
	    	format.xml { render :xml => @user.errors, :status => :unprocessable_entity }
	    end
	    end
	end

	def show
		@user = User.find(params[:id])
		@img = @user.imgs.new
		respond_to do |format|
	      format.html # show.html.erb
	      format.json { render json: @user }
	    end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])

    	respond_to do |format|
      	if @user.update_attributes(params[:user])
        	format.html { redirect_to @user, notice: 'User was successfully updated.' }
        	format.json { head :no_content }
      	else
        	format.html { render action: "edit" }
        	format.json { render json: @user.errors, status: :unprocessable_entity }
      	end
    	end
	end

	def destroy
		@user = User.find(params[:id])
		if @user.destroy	
			flash[:notice] = "User deleted."
			redirect_to users_url
		else
			flash[:error] = "User not deleted."
			redirect_to users_url
		end	
	end

end

PhotoArt/app/helpers/application_helper.rb
module ApplicationHelper
end

PhotoArt/app/helpers/imgs_helper.rb
module ImgsHelper
end

PhotoArt/app/helpers/pages_controller_helper.rb
module PagesControllerHelper
end

PhotoArt/app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

PhotoArt/app/helpers/users_helper.rb
module UsersHelper
end

PhotoArt/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photoart</title>
  <%= stylesheet_link_tag    "bootstrap", :media => "all" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>

  <%= csrf_meta_tags %>
</head>
<body>

 <div class="navbar navbar-fixed-top">
        	<div class="navbar-inner">
            	<div class="logo pull-left">LOGO</div>
                <div class="row-fluid inline">
                <div class="span4 pull-right">
                    	<div class="navbar-itens pull-right">
                			<div class="sign-up">
                                 <div id="nav">
                                    <% if current_user %>
                                        <%= link_to "Edit Profile", edit_user_path(current_user.id)%>
                                        <%= link_to "Logout", :logout%>
                                    <% else %>
                                        <%= link_to "Register", new_user_path%> |
                                        <%= link_to "Login", :login %>
                                    <% end %>
                                </div>
                                </div>
                    		</div>
                		</div>
                    </div>
                	<div class="span8 offset8">
                    	<div class="menu-top">
                                <li class="btn"><%= link_to "Home", users_url %></li>
                                <li class="btn"><%= link_to "Public", users_url %></li>
                                <% if current_user %>
                                    <li class="btn"><%= link_to "Upload", user_url(current_user.id)%></li>
                                <% end %>
                                <li class="btn"><%= link_to "About", users_url %></li>
                                <li class="btn"><%= link_to "Contact", users_url %></li>
                		</div>
                    </div>
                </div>
            </div>
        </div>

	<div class="container">

		<%= yield %>

	</div>
	<br><br>
	<div class="footer">
        	<div class="span12 offset4">
            <p>&#169; Company 2013</p>
        </div>
    </div>


</body>
</html>

PhotoArt/app/views/pages_controller/about.html.erb
<div class="about_title"><h3>About PhotoArt</h3></div>
            <p><p>
            <div class="about_content">
            <p>
            Aliquam posuere augue vitae augue suscipit gravida. Nullam tincidunt commodo augue. Nullam quis leo at dolor scelerisque tempus. Mauris cursus consequat nisi, aliquet sollicitudin mauris mattis ut. Pellentesque et magna vel ante sagittis luctus at eu risus. Integer nec purus in tellus convallis rutrum. Nunc congue turpis at tellus tempus viverra. Pellentesque fringilla pulvinar sem, rutrum egestas magna bibendum nec. Morbi non orci eget lectus congue suscipit. Proin euismod adipiscing nibh, id iaculis nisi ultrices sit amet. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In hac habitasse platea dictumst. Aliquam metus purus, consectetur eget consectetur ornare, blandit id lacus. Donec faucibus neque non neque pharetra id dictum est aliquam. Nunc id mi quam.</p>
            
            <p>Nam tristique bibendum odio sed cursus. Aliquam adipiscing pretium nisl id imperdiet. Praesent lorem lectus, dignissim eu cursus vitae, feugiat vel mi. Vestibulum a orci urna, vel scelerisque ipsum. Ut at eleifend augue. Sed ac pretium nibh. Curabitur ultrices semper augue, vitae pretium nisl consectetur non. Etiam id elit in eros commodo semper id at lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            
            <p>Nam porttitor adipiscing magna, quis rhoncus augue dapibus non. Cras massa metus, pharetra non blandit ut, volutpat id justo. Maecenas sed posuere leo. Nam quis lectus ut ligula adipiscing auctor. Integer eleifend, augue sed elementum varius, neque lorem gravida ligula, et posuere orci neque id turpis. Donec tempor ultrices placerat. Cras tristique dignissim felis sed dapibus. Integer ac posuere eros. Vestibulum pharetra risus vel elit interdum tincidunt. Nam sed tellus ipsum, ac dapibus metus. Duis eu lectus at eros pretium tincidunt eget et urna. Quisque varius vulputate urna, nec faucibus ligula euismod in. Vestibulum pretium convallis libero in sodales. Vivamus cursus enim in metus iaculis rutrum. Mauris ut libero nulla, eget sagittis urna. In consectetur egestas feugiat.</p>
            
            <p>Aliquam erat volutpat. Sed a neque elit. Integer aliquam volutpat augue, quis cursus lorem rutrum id. Ut elementum augue quis urna sagittis ut viverra urna aliquet. Nam a fringilla quam. Cras tempor ornare orci nec lobortis. Suspendisse cursus risus eget massa vehicula vitae fermentum dolor consequat. Morbi sed est lorem. Nulla ac justo quis magna tempor fringilla sit amet id nisi. Pellentesque justo augue, ornare at imperdiet eu, tincidunt aliquet risus. Donec fermentum malesuada erat, ut rhoncus turpis porta vitae. Praesent dictum euismod dolor, vitae sollicitudin velit rhoncus vitae.</p>
            
            <p>Aenean eget tristique augue. Aliquam erat volutpat. Nam aliquam lobortis neque vitae pellentesque. Morbi quis sapien eu ante aliquam suscipit. Suspendisse condimentum malesuada lorem a tristique. Proin vel enim sit amet urna dictum blandit in quis nisl. Proin laoreet varius purus eu mattis. In nec justo mi, ut lacinia nibh.</p>
            
            <p>Integer ut mattis sapien. Pellentesque a lacus massa, non iaculis eros. Phasellus tristique velit sit amet arcu accumsan sed vehicula tortor bibendum. Aliquam leo magna, fringilla at adipiscing nec, aliquam a sem. In sit amet enim justo. Nullam et egestas est. Vivamus mi dolor, ornare et tristique in, vulputate at leo.</p>
            
            <p>Quisque nec sapien sed leo sollicitudin blandit. Proin euismod tristique dignissim. Maecenas placerat gravida nisl quis ultricies. Quisque ac enim risus. Nam ac eros nec neque volutpat varius vitae in elit. Etiam id sapien arcu. Sed iaculis, orci quis faucibus facilisis, elit sapien aliquet dolor, non congue est metus non nisl. </p>

            </div>	
            <p><p><br>
        </div>

PhotoArt/app/views/pages_controller/contact.html.erb
<h2>Contact us</h2>

<label><b>email:</b><p>obscuremetaller@gmail.com</p></label>
<br>
<label><b>twitter:</b><p>@gustafy</p></label>
<br>
<label><b>facebook:</b><p>www.facebook.com/gustavfy</p></label>

PhotoArt/app/views/pages_controller/home.html.erb
<div class="hero-unit">
    <h1>Photo Art</h1>
    <p>Are you an amateur photographer? Do you want to publish your work?<br> Here is the right place? Photo art: A website where you can share your work and know what people think about it. Upload now your pictures!!</p>
    <p>
        <a class="btn btn-primary btn-large">
            Get started
        </a>
    </p>
</div>
<div class="row">
	<div class="span12">
    <div class="span3">
	    <h3>Heading</h3>
	    <p>Curabitur egestas velit leo, vel tincidunt dui. Vestibulum feugiat, leo et malesuada tristique, nibh felis commodo leo, ac viverra libero nunc eu sapien. Integer ac lacinia urna. Fusce tortor nisl, aliquam sed vehicula accumsan, rhoncus eget sapien.</p>
	    <a class="btn" href="#">View Details >></a>
    </div>
    <div class="span3">
    <h3>Heading</h3>
      	<p>Curabitur egestas velit leo, vel tincidunt dui. Vestibulum feugiat, leo et malesuada tristique, nibh felis commodo leo, ac viverra libero nunc eu sapien. Integer ac lacinia urna. Fusce tortor nisl, aliquam sed vehicula accumsan, rhoncus eget sapien.</p>
        <a class="btn" href="#">View Details >></a>
    </div>
    <div class="span3">
    	<h3>Heading</h3>
        <p>Curabitur egestas velit leo, vel tincidunt dui. Vestibulum feugiat, leo et malesuada tristique, nibh felis commodo leo, ac viverra libero nunc eu sapien. Integer ac lacinia urna. Fusce tortor nisl, aliquam sed vehicula accumsan, rhoncus eget sapien.</p>
        <a class="btn" href="#">View Details >></a>
    </div>
</div>
</div>
<br><br><br>

PhotoArt/app/views/user_sessions/_form.html.erb
<%= form_for(@user_session) do |f| %>
  <% if @user_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_session.errors.count, "error") %> prohibited this user_session from being saved:</h2>

      <ul>
      <% @user_session.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

PhotoArt/app/views/user_sessions/edit.html.erb
<h1>Editing user_session</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_session %> |
<%= link_to 'Back', user_sessions_path %>

PhotoArt/app/views/user_sessions/index.html.erb
<h1>Listing user_sessions</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_sessions.each do |user_session| %>
  <tr>
    <td><%= user_session.username %></td>
    <td><%= user_session.password %></td>
    <td><%= link_to 'Show', user_session %></td>
    <td><%= link_to 'Edit', edit_user_session_path(user_session) %></td>
    <td><%= link_to 'Destroy', user_session, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User session', new_user_session_path %>

PhotoArt/app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', user_sessions_path %>

PhotoArt/app/views/user_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user_session.username %>
</p>

<p>
  <b>Password:</b>
  <%= @user_session.password %>
</p>


<%= link_to 'Edit', edit_user_session_path(@user_session) %> |
<%= link_to 'Back', user_sessions_path %>

PhotoArt/app/views/users/_form.html.erb
<%= form_for @user do |form| %>
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
 			<ul>
				<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

<label>
	Name:
	<p><%= form.text_field :name %></p>
</label>

 <label>
 	Username:
	<p><%= form.text_field :username %></p>
</label>

<label>
	Email:
	<p><%= form.text_field :email %></p>
</label>

 <label>
 	Password:
	<p><%= form.password_field :password %></p>
</label>

 <label>
	Password Confirmation
	<p><%= form.password_field :password_confirmation %></p>
</label>

<label>
	Location:
	<p><%= form.text_field :location %></p>
</label>

<label>
	About:
	<p><%= form.text_field :about %></p>
</label>

<p><%= form.submit %></p>

<% end %>

PhotoArt/app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= render :partial => 'form' %>

PhotoArt/app/views/users/index.html.erb
<div class="hero-unit">
            	<h1>Photo Art</h1>
            	<p>Are you an amateur photographer? Do you want to publish your work?<br> Here is the right place? Photo art: A website where you can share your work and know what people think about it. Upload now your pictures!!</p>
            	<p>
                    <a class="btn btn-primary btn-large">
                        Get started
                    </a>
            	</p>
         	</div>


<% @users.each do |user| %>

	<h2><%= link_to"#{user.name}", user_url(user) %></h2>
    <p><%= user.about %></p>
    <div class="picture-capsule">
 
        <% user.imgs.each do |img| %>
        <%= image_tag img.pic.url(:medium) %>
        <% end %>
   
    </div>  
	
	<p><%= link_to "Edit", edit_user_url(user) %> -

	 <%= link_to "delete", user, :method => :destroy,
	 data: {confirm:"delete user?"} %></p>

<% end %>

<hr />


<%= link_to "Add New User", new_user_url %>

<hr />

<h1>Listing users</h1>
 <p id="notice"><%= notice %></p>
<table>
<tr>
<th>Username</th>
<th>Email</th>
<th></th>
<th></th>
<th></th>
</tr>
 
<% @users.each do |user| %>
<tr>
<td><%= user.name %></td>
<td><%= user.username %></td>
<td><%= user.email %></td>
<td><%= link_to 'Show', user %></td>
<td><%= link_to 'Edit', edit_user_path(user) %></td>
<td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
</tr>
<% end %>
</table>
 
<br />
 
<%= link_to 'New User', new_user_path %>

PhotoArt/app/views/users/new.html.erb
<div class="span12">

	<h1>New User</h1>

	<%= form_for @user do |form| %>

	<label>
		Name:
		<p><%= form.text_field :name %></p>
	</label>

	<label>
		Username:
		<p><%= form.text_field :username %></p>
	</label>

	<label>
		Email:
		<p><%= form.text_field :email %></p>
	</label>

	<label>
		Password:
		<p><%= form.password_field :password %></p>
	</label>

	 <label>
	 	Password Confirmation
		<p><%= form.password_field :password_confirmation %></p>
	</label>

	<label>
		Location:
		<p><%= form.text_field :location %></p>
	</label>

	<label>
		About:
		<p><%= form.text_field :about %></p>
	</label>

	<p><%= form.submit %></p>

	<% end %>
</div>

PhotoArt/app/views/users/show.html.erb
<h2><%= @user.name %></h2>
<p><%= @user.about %></p>

<ul>
	<% @user.imgs.each do |img| %>
	<li><%= img.description %><br>
		<%= image_tag img.pic.url(:thumb) %>
	</li>
	<% end %>
</ul>

<%= form_for [@user, @img] do |form| %>
	<p><%= form.text_field :description %><br>
	<%= form.file_field :pic %><br>
 	<%= form.submit %></p>
<% end %>
<hr />

<%= link_to "Back to all users", users_url %>